language: cpp

compiler:
  - gcc

install:
udo apt-get -qq update
sudo apt-get -qq install libglew-dev 

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DTHREE_HEADER_ONLY:BOOL=OFF

script: make